// Renders the ongoing/completed certification lists from data.json. Pure
// client-side rendering of a static, repo-committed data file -- there is
// no live Notion API call from the browser (that would require exposing a
// Notion token client-side, which this site deliberately never does). The
// data file itself is regenerated periodically by re-reading Notion
// directly (see README.md for the refresh process) and committing the
// result, the same "static artifact regenerated by a separate process"
// pattern market-dashboard's data.json already uses.
(function () {
  "use strict";

  var DATA_URL = "data.json";
  var FETCH_TIMEOUT_MS = 10000;

  function fetchJsonWithTimeout(url) {
    var controller = new AbortController();
    var timeoutId = setTimeout(function () {
      controller.abort();
    }, FETCH_TIMEOUT_MS);
    return fetch(url, { signal: controller.signal, referrerPolicy: "no-referrer" })
      .then(function (r) {
        if (!r.ok) throw new Error("bad response");
        return r.json();
      })
      .finally(function () {
        clearTimeout(timeoutId);
      });
  }

  function statusClass(status) {
    if (status === "In progress") return "in-progress";
    if (status === "Done") return "done";
    return "not-started";
  }

  // Lazily fetches and injects a cert's revision-notes HTML fragment the
  // first time its <details> is expanded, rather than loading every cert's
  // notes upfront on page load. The fragment is a build-time-generated
  // trusted file committed alongside data.json (see README.md) -- not user
  // input -- so innerHTML here is a deliberate exception to the
  // textContent-only convention barnyard-hub's own JS uses for genuinely
  // untrusted data (calendar events, to-do text, etc.).
  function wireLazyNotes(details, notesUrl) {
    var body = details.querySelector(".notes-body");
    var loaded = false;
    details.addEventListener("toggle", function () {
      if (!details.open || loaded) return;
      loaded = true;
      body.textContent = "Loading…";
      fetch(notesUrl, { referrerPolicy: "no-referrer" })
        .then(function (r) {
          if (!r.ok) throw new Error("bad response");
          return r.text();
        })
        .then(function (html) {
          // Trusted, build-time-generated HTML fragment -- see comment above.
          body.innerHTML = html;
        })
        .catch(function () {
          body.textContent = "Couldn't load revision notes right now.";
        });
    });
  }

  function buildCertCard(cert, isCompleted) {
    var li = document.createElement("li");
    li.className = "cert-card";

    var head = document.createElement("div");
    head.className = "cert-head";

    var nameEl = document.createElement("p");
    nameEl.className = "cert-name";
    nameEl.textContent = cert.name;
    head.appendChild(nameEl);

    if (!isCompleted && cert.status) {
      var statusEl = document.createElement("span");
      statusEl.className = "cert-status " + statusClass(cert.status);
      statusEl.textContent = cert.status;
      head.appendChild(statusEl);
    }

    li.appendChild(head);

    if (!isCompleted && cert.fullName && cert.fullName !== cert.name) {
      var fullNameEl = document.createElement("p");
      fullNameEl.className = "cert-empty-note";
      fullNameEl.style.marginTop = "2px";
      fullNameEl.textContent = cert.fullName;
      li.appendChild(fullNameEl);
    }

    var links = document.createElement("p");
    links.className = "cert-links";
    var notionLink = document.createElement("a");
    notionLink.href = cert.notionUrl;
    notionLink.target = "_blank";
    notionLink.rel = "noopener noreferrer";
    notionLink.textContent = "View notes in Notion →";
    links.appendChild(notionLink);
    li.appendChild(links);

    if (cert.notesUrl) {
      var details = document.createElement("details");
      details.className = "revision-notes";
      var summary = document.createElement("summary");
      summary.textContent = "Revision notes";
      var body = document.createElement("div");
      body.className = "notes-body";
      details.appendChild(summary);
      details.appendChild(body);
      li.appendChild(details);
      wireLazyNotes(details, cert.notesUrl);
    } else if (!isCompleted) {
      var emptyNote = document.createElement("p");
      emptyNote.className = "cert-empty-note";
      emptyNote.textContent =
        cert.status === "Not started"
          ? "No notes yet — not started."
          : "No revision notes generated yet.";
      li.appendChild(emptyNote);
    }

    return li;
  }

  function render(data) {
    var ongoingList = document.getElementById("ongoing-list");
    var completedList = document.getElementById("completed-list");
    var generatedNote = document.getElementById("generated-note");

    if (ongoingList) {
      (data.ongoing || []).forEach(function (cert) {
        ongoingList.appendChild(buildCertCard(cert, false));
      });
    }
    if (completedList) {
      (data.completed || []).forEach(function (cert) {
        completedList.appendChild(buildCertCard(cert, true));
      });
    }
    if (generatedNote && data.generated) {
      generatedNote.textContent = "Last synced from Notion: " + data.generated;
    }
  }

  function renderError() {
    var main = document.getElementById("main-content");
    if (!main) return;
    var p = document.createElement("p");
    p.className = "cert-empty-note";
    p.textContent = "Couldn't load certification data right now.";
    main.appendChild(p);
  }

  if (typeof document !== "undefined") {
    document.addEventListener("DOMContentLoaded", function () {
      fetchJsonWithTimeout(DATA_URL).then(render).catch(renderError);
    });
  }

  // Expose pure, DOM-free helpers to the Node-based test file at
  // test/app.test.js -- same module.exports-guard pattern barnyard-hub's
  // glance-widgets.js/live-prices.js already use (a no-op in the browser,
  // since `module` is undefined there).
  if (typeof module !== "undefined" && module.exports) {
    module.exports = {
      statusClass: statusClass
    };
  }
})();
