// Renders the ongoing/completed certification lists from data.json. Pure
// client-side rendering of a static, repo-committed data file -- there is
// no live Notion API call from the browser (that would require exposing a
// Notion token client-side, which this site deliberately never does). The
// data file itself is regenerated periodically by re-reading Notion
// directly (see README.md for the refresh process) and committing the
// result, the same "static artifact regenerated by a separate process"
// pattern market-dashboard's data.json already uses.
//
// The one exception: the "Generate revision notes" button hits a Cloudflare
// Worker (api.barnyard.site/generate-notes) that itself fetches Notion
// server-side and calls Claude -- see ClaudeRepo/cloudflare-worker's README
// for the full setup, cost, and abuse-mitigation this represents. Freshly
// generated notes are cached in this browser's own localStorage only (not
// synced anywhere, not shared across devices/visitors, expires after
// NOTES_CACHE_MAX_AGE_MS) so a repeat visit doesn't re-trigger a paid call
// for content that hasn't changed.
(function () {
  "use strict";

  var DATA_URL = "data.json";
  var FETCH_TIMEOUT_MS = 10000;
  var GENERATE_NOTES_API = "https://api.barnyard.site/generate-notes";
  // Switched off 2026-10-08. The "Generate revision notes" button called the paid Claude
  // API through the Worker; revision notes are now made from the study notebook with the
  // site's own model (Notes -> "Generate KB article (AI)"). The Worker route answers 410
  // too. Notes already generated stay readable from this browser's cache. To bring the
  // button back, set this to true and set the Worker variable GENERATE_NOTES_ENABLED to "1".
  var GENERATE_NOTES_ENABLED = false;
  var GENERATE_TIMEOUT_MS = 65000; // slightly past the Worker's own 60s Claude-call timeout, so the client doesn't give up first
  var NOTES_CACHE_PREFIX = "study-hub-notes:";
  var NOTES_CACHE_VERSION = 1;
  var NOTES_CACHE_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days -- past this, treat as stale and fall back to the static fragment (if any) or a fresh "Generate" prompt, rather than showing content of unknown vintage as if current indefinitely

  function fetchWithTimeout(url, parseAs) {
    var controller = new AbortController();
    var timeoutId = setTimeout(function () {
      controller.abort();
    }, FETCH_TIMEOUT_MS);
    return fetch(url, { signal: controller.signal, referrerPolicy: "no-referrer" })
      .then(function (r) {
        if (!r.ok) throw new Error("bad response");
        return parseAs === "text" ? r.text() : r.json();
      })
      .finally(function () {
        clearTimeout(timeoutId);
      });
  }

  // Same shape as fetchWithTimeout's text mode, but takes an
  // externally-owned AbortController so a caller (wireNotesArea) can cancel
  // an in-flight static-fragment load from outside -- needed to fix a real
  // race: a slow static load finishing just after a faster, successful
  // generation could otherwise silently overwrite freshly generated (and
  // paid-for) notes. See wireNotesArea's own comment.
  function fetchTextWithController(url, controller) {
    var timeoutId = setTimeout(function () {
      controller.abort();
    }, FETCH_TIMEOUT_MS);
    return fetch(url, { signal: controller.signal, referrerPolicy: "no-referrer" })
      .then(function (r) {
        if (!r.ok) throw new Error("bad response");
        return r.text();
      })
      .finally(function () {
        clearTimeout(timeoutId);
      });
  }

  function statusClass(status) {
    if (status === "In progress") return "in-progress";
    if (status === "Done") return "done";
    return "not-started";
  }

  // Guards against a malformed data.json entry (missing/renamed field from
  // a future Notion-side edit) rendering the literal string "undefined" --
  // textContent = undefined stringifies to "undefined" (only null maps to
  // empty), and an absent notionUrl would otherwise produce a live-looking
  // href="undefined" link that 404s. Pure/DOM-free so it's unit-testable.
  function normalizeCert(cert) {
    cert = cert || {};
    var name = typeof cert.name === "string" && cert.name ? cert.name : "(untitled certification)";
    var fullName = typeof cert.fullName === "string" && cert.fullName && cert.fullName !== name ? cert.fullName : null;
    var status = typeof cert.status === "string" && cert.status ? cert.status : null;
    var notionUrl = typeof cert.notionUrl === "string" && cert.notionUrl.indexOf("https://") === 0 ? cert.notionUrl : null;
    var notesUrl = typeof cert.notesUrl === "string" && cert.notesUrl ? cert.notesUrl : null;
    // Must match a key in the Worker's own CERT_NOTION_PAGES allowlist
    // (cloudflare-worker/src/index.js) -- a slug with no matching server-side
    // entry just gets a generic "unknown certification" error back, handled
    // like any other failure.
    var slug = typeof cert.slug === "string" && /^[a-z0-9-]+$/.test(cert.slug) ? cert.slug : null;
    return { name: name, fullName: fullName, status: status, notionUrl: notionUrl, notesUrl: notesUrl, slug: slug };
  }

  function notesCacheKey(slug) {
    return NOTES_CACHE_PREFIX + slug;
  }

  // Rejects a cache entry that's the wrong schema version, malformed, or
  // older than NOTES_CACHE_MAX_AGE_MS -- see that constant's own comment.
  function loadCachedNotes(slug) {
    try {
      var raw = window.localStorage.getItem(notesCacheKey(slug));
      if (!raw) return null;
      var parsed = JSON.parse(raw);
      if (!parsed || parsed.v !== NOTES_CACHE_VERSION) return null;
      if (!Array.isArray(parsed.sections) || !parsed.sections.length) return null;
      if (typeof parsed.generatedAt !== "string") return null;
      var ageMs = Date.now() - new Date(parsed.generatedAt).getTime();
      if (!Number.isFinite(ageMs) || ageMs < 0 || ageMs > NOTES_CACHE_MAX_AGE_MS) return null;
      return parsed;
    } catch (err) {
      return null;
    }
  }

  function saveCachedNotes(slug, sections) {
    try {
      window.localStorage.setItem(
        notesCacheKey(slug),
        JSON.stringify({ v: NOTES_CACHE_VERSION, sections: sections, generatedAt: new Date().toISOString() })
      );
    } catch (err) {
      // localStorage unavailable/full/private-browsing -- the freshly
      // generated notes still render for this page view, just won't persist
      // across a reload. Not worth surfacing as an error for a caching
      // nicety.
    }
  }

  function formatGeneratedAt(iso) {
    try {
      var d = new Date(iso);
      if (isNaN(d.getTime())) return null;
      return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
    } catch (err) {
      return null;
    }
  }

  // How old the Notion snapshot is, in words. `generated` is data.json's
  // plain "YYYY-MM-DD" date; a snapshot older than SYNC_STALE_DAYS is flagged,
  // since a stale list reads exactly like a current one. An unparsable date
  // falls back to the raw text and is never flagged.
  var SYNC_STALE_DAYS = 14;
  function describeSync(generated, now) {
    var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(generated);
    if (!m) return { text: "Last synced from Notion: " + generated, stale: false, days: null };
    var then = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
    var today = new Date(now);
    today = new Date(today.getFullYear(), today.getMonth(), today.getDate());
    var days = Math.max(0, Math.round((today.getTime() - then.getTime()) / 86400000));
    var when = then.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
    if (days >= SYNC_STALE_DAYS) return { text: "Notion sync is " + days + " days old (last synced " + when + ")", stale: true, days: days };
    return { text: "Last synced from Notion on " + when, stale: false, days: days };
  }

  // Renders Claude-generated sections via createElement/textContent only --
  // unlike the pre-authored notes/*.html fragments (trusted, build-time
  // content, injected via innerHTML further down), this content is
  // model-generated at request time and gets the same safe-rendering
  // treatment this site already uses for genuinely untrusted data, even
  // though the Worker itself also validates the shape server-side before
  // ever sending it here.
  function renderGeneratedSections(container, sections) {
    container.textContent = "";
    sections.forEach(function (section) {
      var h3 = document.createElement("h3");
      h3.textContent = section && typeof section.heading === "string" ? section.heading : "";
      container.appendChild(h3);
      var ul = document.createElement("ul");
      ((section && section.items) || []).forEach(function (item) {
        var itemEl = document.createElement("li");
        itemEl.textContent = typeof item === "string" ? item : "";
        ul.appendChild(itemEl);
      });
      container.appendChild(ul);
    });
  }

  function requestGeneratedNotes(slug) {
    var controller = new AbortController();
    var timeoutId = setTimeout(function () {
      controller.abort();
    }, GENERATE_TIMEOUT_MS);
    return fetch(GENERATE_NOTES_API, {
      method: "POST",
      signal: controller.signal,
      referrerPolicy: "no-referrer",
      // Required now that /generate-notes checks a login session -- without
      // this the browser never sends the session cookie cross-origin at
      // all, and every call 401s regardless of login state (2026-09-02
      // security review, M2).
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ slug: slug })
    })
      .then(function (r) {
        return r
          .json()
          .catch(function () {
            return null;
          })
          .then(function (data) {
            if (!r.ok) {
              throw new Error(data && typeof data.error === "string" ? data.error : "request failed");
            }
            if (!data || !Array.isArray(data.sections) || !data.sections.length) {
              throw new Error("malformed response");
            }
            return data.sections;
          });
      })
      .finally(function () {
        clearTimeout(timeoutId);
      });
  }

  // Maps a requestGeneratedNotes() failure to user-facing copy. Only the
  // Worker's own 400/422 messages (both written to be shown to a visitor)
  // are passed through as-is; everything else -- a network failure, a CSP
  // block, an aborted 65s timeout, a generic Worker 5xx -- gets a fixed,
  // friendly fallback instead of a raw technical string like "Failed to
  // fetch" or "The user aborted a request" (which reads as blaming the
  // visitor for a timeout they didn't cause).
  function friendlyGenerateError(err) {
    if (err && err.name === "AbortError") {
      return "Generation took longer than expected and timed out. Try again.";
    }
    if (err instanceof TypeError) {
      return "Couldn't reach the notes service. Check your connection and try again.";
    }
    var msg = err && typeof err.message === "string" ? err.message : "";
    // These two are genuinely different states, not one generic "not
    // allowed" -- the client-side login gate below (see wireNotesArea)
    // should normally prevent "unauthenticated" from ever reaching here,
    // but auth state can go stale between page load and a click, so this
    // stays as the honest fallback either way. "forbidden" means logged in
    // but missing the AD group this action requires -- the client-side gate
    // can't know that in advance, since /auth/session deliberately doesn't
    // return group membership (see the Worker's own /auth/* section).
    if (msg === "unauthenticated") {
      return "You're not logged in. Log in and try again.";
    }
    if (msg === "forbidden") {
      return "You're logged in, but don't have access to generate notes.";
    }
    if (msg === "unknown certification" || msg === "not enough content in Notion yet to generate notes") {
      return "Couldn't generate revision notes: " + msg + ".";
    }
    return "Couldn't generate revision notes right now. Try again in a moment.";
  }

  function makeGenerateButton(label) {
    var btn = document.createElement("button");
    btn.type = "button";
    btn.className = "generate-notes-btn";
    btn.textContent = label;
    return btn;
  }

  // Owns everything under a cert's "Revision notes" <details>: the
  // pre-authored static fragment (if any), the localStorage-cached
  // generated version (if any), and the Generate/Regenerate button (if the
  // cert has a slug). `certRef` is `{ notesUrl, slug }` -- `slug` is
  // expected to already be null for a completed cert or one without a real
  // slug, so this function itself doesn't need to know about `isCompleted`.
  //
  // The one subtlety worth documenting: a static fragment load and a
  // generation request can legitimately overlap (the static load's own 10s
  // timeout is close to generation's advertised 10-20s), and a naive
  // implementation lets whichever one resolves LAST win, regardless of
  // which one is actually more current. `contentSource` tracks which kind
  // of content is currently authoritative; once it flips to "generated"
  // (from either a cache hit at wiring time or a successful live
  // generation), the static-fragment code checks it before ever writing to
  // `body` and aborts its own in-flight fetch via `staticController` the
  // moment a generation succeeds, so a static response that arrives after
  // that point is simply discarded instead of overwriting the freshly
  // generated (and, for a live generation, already paid-for) content.
  function wireNotesArea(details, body, certRef, cachedNotes, authState) {
    var contentSource = cachedNotes ? "generated" : null;
    var staticLoaded = false;
    var staticController = null;

    var status = document.createElement("p");
    status.className = "cert-empty-note";
    status.setAttribute("role", "status");
    status.hidden = true;

    var generatedNote = document.createElement("p");
    generatedNote.className = "cert-empty-note";
    generatedNote.hidden = true;

    var hint = null;
    var button = null;

    function setStatus(text) {
      if (!text) {
        status.hidden = true;
        status.textContent = "";
        return;
      }
      status.textContent = text;
      status.hidden = false;
    }

    function showGenerated(sections, generatedAtIso) {
      contentSource = "generated";
      renderGeneratedSections(body, sections);
      var formatted = generatedAtIso ? formatGeneratedAt(generatedAtIso) : null;
      if (formatted) {
        generatedNote.textContent = "Generated " + formatted + " in this browser.";
        generatedNote.hidden = false;
      } else {
        generatedNote.hidden = true;
      }
      if (button) button.textContent = "Regenerate notes";
    }

    if (cachedNotes) showGenerated(cachedNotes.sections, cachedNotes.generatedAt);

    if (GENERATE_NOTES_ENABLED && certRef.slug && authState && authState.authenticated) {
      // Cost/latency disclosure shown up front, before any click -- not
      // only inside the in-flight status message, which a first-time
      // visitor would only see after the (irreversible, billed) request is
      // already running.
      hint = document.createElement("p");
      hint.className = "cert-empty-note";
      hint.textContent = "Uses the Claude API to summarize your Notion notes — takes 10–20 seconds.";

      button = makeGenerateButton(cachedNotes || certRef.notesUrl ? "Regenerate notes" : "Generate revision notes");
      button.addEventListener("click", function () {
        button.disabled = true;
        button.setAttribute("aria-busy", "true");
        // A generation that's about to start always supersedes any
        // in-flight static-fragment load -- see this function's own
        // comment on the race this prevents.
        if (staticController) staticController.abort();
        setStatus("Generating…");

        requestGeneratedNotes(certRef.slug)
          .then(function (sections) {
            saveCachedNotes(certRef.slug, sections);
            setStatus(null);
            showGenerated(sections, new Date().toISOString());
          })
          .catch(function (err) {
            setStatus(friendlyGenerateError(err));
          })
          .finally(function () {
            button.disabled = false;
            button.removeAttribute("aria-busy");
          });
      });
    } else if (GENERATE_NOTES_ENABLED && certRef.slug) {
      // Not logged in (or auth state couldn't be checked -- fails closed to
      // this state, same as barnyardAuthState()'s own fallback) -- show a
      // login prompt in place of an active button, rather than letting a
      // click reach the server just to bounce off a 401. Viewing already-
      // cached notes above is unaffected -- only starting a NEW generation
      // needs a session.
      hint = document.createElement("p");
      hint.className = "cert-empty-note";
      hint.textContent = "Log in to generate revision notes for this certification.";

      button = document.createElement("a");
      button.className = "generate-notes-btn";
      button.href = typeof window.barnyardLoginUrl === "function" ? window.barnyardLoginUrl() : "https://api.barnyard.site/auth/login";
      button.textContent = "Log in to generate notes";
    }

    if (certRef.notesUrl) {
      details.addEventListener("toggle", function () {
        if (!details.open || staticLoaded || contentSource === "generated") return;
        staticLoaded = true;
        staticController = new AbortController();
        body.textContent = "Loading…";
        fetchTextWithController(certRef.notesUrl, staticController)
          .then(function (html) {
            if (contentSource === "generated") return; // superseded while this was in flight
            // Trusted, build-time-generated HTML fragment -- not user
            // input -- so innerHTML here is a deliberate exception to the
            // textContent-only rendering used for the generated-content
            // path above.
            body.innerHTML = html;
          })
          .catch(function (err) {
            if (contentSource === "generated" || (err && err.name === "AbortError")) return; // superseded, not a real failure
            staticLoaded = false; // allow retry on collapse/reopen
            body.textContent = "Couldn't load revision notes right now. Collapse and expand to retry.";
          });
      });
    } else if (certRef.slug && !cachedNotes) {
      // Nothing pre-authored and nothing cached yet -- an empty disclosure
      // reads as broken when first expanded, so seed it with an explicit
      // prompt instead of leaving it blank.
      var seed = document.createElement("p");
      seed.className = "cert-empty-note";
      seed.textContent = "No notes yet — generate them from your Notion page.";
      body.appendChild(seed);
    }

    return { hint: hint, button: button, status: status, generatedNote: generatedNote };
  }

  function buildCertCard(rawCert, isCompleted, authState) {
    var cert = normalizeCert(rawCert);
    var li = document.createElement("li");
    li.className = "cert-card";

    var head = document.createElement("div");
    head.className = "cert-head";

    var nameEl = document.createElement("p");
    nameEl.className = "cert-name";
    nameEl.textContent = cert.name;
    head.appendChild(nameEl);

    if (!isCompleted && cert.status) {
      var statusEl = document.createElement("span");
      statusEl.className = "cert-status " + statusClass(cert.status);
      statusEl.textContent = cert.status;
      head.appendChild(statusEl);
    }

    li.appendChild(head);

    if (!isCompleted && cert.fullName) {
      var fullNameEl = document.createElement("p");
      fullNameEl.className = "cert-fullname";
      fullNameEl.textContent = cert.fullName;
      li.appendChild(fullNameEl);
    }

    if (cert.notionUrl) {
      var links = document.createElement("p");
      links.className = "cert-links";
      var notionLink = document.createElement("a");
      notionLink.href = cert.notionUrl;
      notionLink.target = "_blank";
      notionLink.rel = "noopener noreferrer";
      notionLink.textContent = "View notes in Notion →";
      links.appendChild(notionLink);
      li.appendChild(links);
    }

    // Generation is only ever offered for non-completed certs: a completed
    // cert keeping its slug (nothing requires clearing it -- see README)
    // would otherwise get a live, paid "Regenerate" button whose result the
    // page never reads back on a later visit, since the cache lookup below
    // is also gated on !isCompleted -- a pay-per-click control with no
    // lasting effect. See the 2026-08-23 review finding this closes.
    var effectiveSlug = !isCompleted ? cert.slug : null;
    var cachedNotes = effectiveSlug ? loadCachedNotes(effectiveSlug) : null;

    if (cert.notesUrl || cachedNotes || effectiveSlug) {
      var details = document.createElement("details");
      details.className = "revision-notes";
      var summary = document.createElement("summary");
      summary.textContent = "Revision notes";
      var body = document.createElement("div");
      body.className = "notes-body";
      details.appendChild(summary);
      details.appendChild(body);

      var parts = wireNotesArea(details, body, { notesUrl: cert.notesUrl, slug: effectiveSlug }, cachedNotes, authState);
      if (parts.hint) details.appendChild(parts.hint);
      if (parts.button) details.appendChild(parts.button);
      details.appendChild(parts.status);
      details.appendChild(parts.generatedNote);

      li.appendChild(details);
    } else if (!isCompleted) {
      var emptyNote = document.createElement("p");
      emptyNote.className = "cert-empty-note";
      emptyNote.textContent =
        cert.status === "Not started"
          ? "No notes yet — not started."
          : "No revision notes generated yet.";
      li.appendChild(emptyNote);
    }

    return li;
  }

  function loadingNoteEl() {
    return document.getElementById("loading-note");
  }

  function render(data, authState) {
    var ongoingList = document.getElementById("ongoing-list");
    var completedList = document.getElementById("completed-list");
    var generatedNote = document.getElementById("generated-note");
    var loadingNote = loadingNoteEl();
    if (loadingNote) loadingNote.remove();

    if (ongoingList) {
      (data.ongoing || []).forEach(function (cert) {
        ongoingList.appendChild(buildCertCard(cert, false, authState));
      });
    }
    if (completedList) {
      (data.completed || []).forEach(function (cert) {
        completedList.appendChild(buildCertCard(cert, true, authState));
      });
    }
    if (generatedNote && typeof data.generated === "string" && data.generated) {
      var sync = describeSync(data.generated, Date.now());
      generatedNote.textContent = sync.text;
      if (sync.stale) generatedNote.classList.add("is-stale");
    }
  }

  function renderError() {
    var loadingNote = loadingNoteEl();
    if (loadingNote) {
      loadingNote.textContent = "Couldn't load certification data right now.";
      return;
    }
    var main = document.getElementById("main-content");
    if (!main) return;
    var p = document.createElement("p");
    p.className = "cert-empty-note";
    p.textContent = "Couldn't load certification data right now.";
    main.insertBefore(p, main.firstChild);
  }

  if (typeof document !== "undefined") {
    document.addEventListener("DOMContentLoaded", function () {
      // barnyardAuthState() (from auth-gate.js, loaded before this file --
      // see index.html's script order) always resolves, never rejects (see
      // its own comment), so Promise.all here can't fail because of it --
      // only a real data.json failure reaches renderError below. Falls back
      // to "not authenticated" if auth-gate.js somehow isn't loaded, same
      // fail-closed treatment used throughout.
      var authStatePromise =
        typeof window.barnyardAuthState === "function"
          ? window.barnyardAuthState()
          : Promise.resolve({ authenticated: false });
      Promise.all([fetchWithTimeout(DATA_URL, "json"), authStatePromise])
        .then(function (results) {
          render(results[0], results[1]);
        })
        .catch(renderError);
    });
  }

  // Expose pure, DOM-free helpers to the Node-based test file at
  // test/app.test.js -- same module.exports-guard pattern barnyard-hub's
  // glance-widgets.js/live-prices.js already use (a no-op in the browser,
  // since `module` is undefined there).
  if (typeof module !== "undefined" && module.exports) {
    module.exports = {
      statusClass: statusClass,
      normalizeCert: normalizeCert,
      friendlyGenerateError: friendlyGenerateError,
      loadCachedNotes: loadCachedNotes,
      saveCachedNotes: saveCachedNotes,
      formatGeneratedAt: formatGeneratedAt,
      describeSync: describeSync
    };
  }
})();
