// Renders the ongoing/completed certification lists from data.json. Pure
// client-side rendering of a static, repo-committed data file -- there is
// no live Notion API call from the browser (that would require exposing a
// Notion token client-side, which this site deliberately never does). The
// data file itself is regenerated periodically by re-reading Notion
// directly (see README.md for the refresh process) and committing the
// result, the same "static artifact regenerated by a separate process"
// pattern market-dashboard's data.json already uses.
(function () {
  "use strict";

  var DATA_URL = "data.json";
  var FETCH_TIMEOUT_MS = 10000;

  function fetchWithTimeout(url, parseAs) {
    var controller = new AbortController();
    var timeoutId = setTimeout(function () {
      controller.abort();
    }, FETCH_TIMEOUT_MS);
    return fetch(url, { signal: controller.signal, referrerPolicy: "no-referrer" })
      .then(function (r) {
        if (!r.ok) throw new Error("bad response");
        return parseAs === "text" ? r.text() : r.json();
      })
      .finally(function () {
        clearTimeout(timeoutId);
      });
  }

  function statusClass(status) {
    if (status === "In progress") return "in-progress";
    if (status === "Done") return "done";
    return "not-started";
  }

  // Guards against a malformed data.json entry (missing/renamed field from
  // a future Notion-side edit) rendering the literal string "undefined" --
  // textContent = undefined stringifies to "undefined" (only null maps to
  // empty), and an absent notionUrl would otherwise produce a live-looking
  // href="undefined" link that 404s. Pure/DOM-free so it's unit-testable.
  function normalizeCert(cert) {
    cert = cert || {};
    var name = typeof cert.name === "string" && cert.name ? cert.name : "(untitled certification)";
    var fullName = typeof cert.fullName === "string" && cert.fullName && cert.fullName !== name ? cert.fullName : null;
    var status = typeof cert.status === "string" && cert.status ? cert.status : null;
    var notionUrl = typeof cert.notionUrl === "string" && cert.notionUrl.indexOf("https://") === 0 ? cert.notionUrl : null;
    var notesUrl = typeof cert.notesUrl === "string" && cert.notesUrl ? cert.notesUrl : null;
    return { name: name, fullName: fullName, status: status, notionUrl: notionUrl, notesUrl: notesUrl };
  }

  // Lazily fetches and injects a cert's revision-notes HTML fragment the
  // first time its <details> is expanded, rather than loading every cert's
  // notes upfront on page load. The fragment is a build-time-generated
  // trusted file committed alongside data.json (see README.md) -- not user
  // input -- so innerHTML here is a deliberate exception to the
  // textContent-only convention barnyard-hub's own JS uses for genuinely
  // untrusted data (calendar events, to-do text, etc.).
  //
  // `loaded` resets to false on failure (timeout, 404, network error) so
  // collapsing and re-expanding the <details> retries, rather than leaving
  // a permanent error with no way to recover short of a full page reload.
  function wireLazyNotes(details, notesUrl) {
    var body = details.querySelector(".notes-body");
    var loaded = false;
    details.addEventListener("toggle", function () {
      if (!details.open || loaded) return;
      loaded = true;
      body.textContent = "Loading…";
      fetchWithTimeout(notesUrl, "text")
        .then(function (html) {
          // Trusted, build-time-generated HTML fragment -- see comment above.
          body.innerHTML = html;
        })
        .catch(function () {
          loaded = false;
          body.textContent = "Couldn't load revision notes right now. Collapse and expand to retry.";
        });
    });
  }

  function buildCertCard(rawCert, isCompleted) {
    var cert = normalizeCert(rawCert);
    var li = document.createElement("li");
    li.className = "cert-card";

    var head = document.createElement("div");
    head.className = "cert-head";

    var nameEl = document.createElement("p");
    nameEl.className = "cert-name";
    nameEl.textContent = cert.name;
    head.appendChild(nameEl);

    if (!isCompleted && cert.status) {
      var statusEl = document.createElement("span");
      statusEl.className = "cert-status " + statusClass(cert.status);
      statusEl.textContent = cert.status;
      head.appendChild(statusEl);
    }

    li.appendChild(head);

    if (!isCompleted && cert.fullName) {
      var fullNameEl = document.createElement("p");
      fullNameEl.className = "cert-fullname";
      fullNameEl.textContent = cert.fullName;
      li.appendChild(fullNameEl);
    }

    if (cert.notionUrl) {
      var links = document.createElement("p");
      links.className = "cert-links";
      var notionLink = document.createElement("a");
      notionLink.href = cert.notionUrl;
      notionLink.target = "_blank";
      notionLink.rel = "noopener noreferrer";
      notionLink.textContent = "View notes in Notion →";
      links.appendChild(notionLink);
      li.appendChild(links);
    }

    if (cert.notesUrl) {
      var details = document.createElement("details");
      details.className = "revision-notes";
      var summary = document.createElement("summary");
      summary.textContent = "Revision notes";
      var body = document.createElement("div");
      body.className = "notes-body";
      details.appendChild(summary);
      details.appendChild(body);
      li.appendChild(details);
      wireLazyNotes(details, cert.notesUrl);
    } else if (!isCompleted) {
      var emptyNote = document.createElement("p");
      emptyNote.className = "cert-empty-note";
      emptyNote.textContent =
        cert.status === "Not started"
          ? "No notes yet — not started."
          : "No revision notes generated yet.";
      li.appendChild(emptyNote);
    }

    return li;
  }

  function loadingNoteEl() {
    return document.getElementById("loading-note");
  }

  function render(data) {
    var ongoingList = document.getElementById("ongoing-list");
    var completedList = document.getElementById("completed-list");
    var generatedNote = document.getElementById("generated-note");
    var loadingNote = loadingNoteEl();
    if (loadingNote) loadingNote.remove();

    if (ongoingList) {
      (data.ongoing || []).forEach(function (cert) {
        ongoingList.appendChild(buildCertCard(cert, false));
      });
    }
    if (completedList) {
      (data.completed || []).forEach(function (cert) {
        completedList.appendChild(buildCertCard(cert, true));
      });
    }
    if (generatedNote && typeof data.generated === "string" && data.generated) {
      generatedNote.textContent = "Last synced from Notion: " + data.generated;
    }
  }

  function renderError() {
    var loadingNote = loadingNoteEl();
    if (loadingNote) {
      loadingNote.textContent = "Couldn't load certification data right now.";
      return;
    }
    var main = document.getElementById("main-content");
    if (!main) return;
    var p = document.createElement("p");
    p.className = "cert-empty-note";
    p.textContent = "Couldn't load certification data right now.";
    main.insertBefore(p, main.firstChild);
  }

  if (typeof document !== "undefined") {
    document.addEventListener("DOMContentLoaded", function () {
      fetchWithTimeout(DATA_URL, "json").then(render).catch(renderError);
    });
  }

  // Expose pure, DOM-free helpers to the Node-based test file at
  // test/app.test.js -- same module.exports-guard pattern barnyard-hub's
  // glance-widgets.js/live-prices.js already use (a no-op in the browser,
  // since `module` is undefined there).
  if (typeof module !== "undefined" && module.exports) {
    module.exports = {
      statusClass: statusClass,
      normalizeCert: normalizeCert
    };
  }
})();
